server:
  port: 8000
  #application name for service discovery
spring:
  application:
    name: service-discovery
  #since this project is service discovery, there's no need for service discovery registration.
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    serviceUrl:
      defaultZone: http://localhost:8000/eureka
  server:
    enable-self-preservation: false